version: '3.3'
services:
  db:
    container_name: fin-org-db
    image: mysql:8.0
    restart: always
    env_file: ".env"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    volumes:
      - /my-db:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: always

  backend:
    container_name: fin-org-backend
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis

volumes:
  my-db:
  redis-data: