version: '3.3'
services:
  db:
    container_name: fin-org-db
    image: mysql:5.7
    restart: always
    env_file: ".env"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: ${DB_HOST}
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    volumes:
      - my-db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  backend:
    container_name: fin-org-backend
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "${PORT}:${PORT}"
    depends_on:
      - db

volumes:
  my-db: